# Auto-generated checkpoint list (do not edit manually)
# Generated by launch_pretrain_array.sh
checkpoint_list=("checkpoints/Tiny Recursion Policy/sn_NTE_cont/step_32540" "checkpoints/Tiny Recursion Policy/sn_NTE_cont/step_32540" "checkpoints/Tiny Recursion Policy/sn_NTE_cont/step_32540" "checkpoints/Tiny Recursion Policy/sn_NTE_cont/step_32540" "checkpoints/Tiny Recursion Policy/sn_NTE_cont/step_32540" "checkpoints/Tiny Recursion Policy/sn_NTE_cont/step_32540" "checkpoints/Tiny Recursion Policy/sn_NTE_cont/step_32540" "checkpoints/Tiny Recursion Policy/sn_NTE_cont/step_32540" )
