#!/bin/bash
#SBATCH --job-name=trm
#SBATCH --output=out/%A/trmarr_%A_%a.out
#SBATCH --error=out/%A/trmarr_%A_%a.err
#SBATCH --array=0-1
#SBATCH --time=36:00:00
#SBATCH --partition=general
#SBATCH --gres=gpu:1
#SBATCH --constraint=VRAM_48GB
#SBATCH --cpus-per-task=4

set -euo pipefail

# Source checkpoint list if it exists (generated by launch_pretrain_array.sh)
checkpoint_file=".checkpoint_list.sh"
if [ -f "$checkpoint_file" ]; then
    source "$checkpoint_file"
else
    # Default: no checkpoints
    checkpoint_list=()
fi

# Define bash arrays for the parameters
time_embed_list=(True False)

# Get values for this task
time_embed_val=${time_embed_list[$SLURM_ARRAY_TASK_ID]}

# Get checkpoint for this task (if available)
# Note: SLURM_ARRAY_TASK_ID is 1-indexed, but bash arrays are 0-indexed
task_idx=$((SLURM_ARRAY_TASK_ID - 1))
if [ ${#checkpoint_list[@]} -gt 0 ] && [ $task_idx -ge 0 ] && [ $task_idx -lt ${#checkpoint_list[@]} ]; then
    checkpoint_val="${checkpoint_list[$task_idx]}"
else
    checkpoint_val=""
fi

if [ "$time_embed_val" = "True" ]; then
    time_embed_abbrev="TE"
elif [ "$time_embed_val" = "False" ]; then
    time_embed_abbrev="NTE"
else
    time_embed_abbrev="unknown"
fi

run_name="${time_embed_abbrev}"

if [ -n "$checkpoint_val" ]; then
    echo "Running task $SLURM_ARRAY_TASK_ID: time_embed=$time_embed_val, run_name=$run_name, checkpoint=$checkpoint_val"
else
    echo "Running task $SLURM_ARRAY_TASK_ID: time_embed=$time_embed_val, run_name=$run_name"
fi

eval "$(conda shell.bash hook)"
conda activate trp

# Run pretrain.py with config overrides
# Use single quotes around value to force string interpretation in Hydra/YAML
python_cmd="python pretrain.py \
  --config-name=cfg_sudoku_mlp \
  arch.time_embeddings=$time_embed_val \
  run_name=\"$run_name\""

# Add checkpoint if specified
if [ -n "$checkpoint_val" ]; then
    python_cmd="$python_cmd load_checkpoint=\"$checkpoint_val\""
fi

eval $python_cmd

echo "Completed task $SLURM_ARRAY_TASK_ID: H_deterministic_mode=$H_deterministic_mode_val, time_embed=$time_embed_val"